import React from 'react';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import Pokedex from '@components/Pokedex';
import { fetchPokedex, fetchPokemon } from '@api/pokemon';
import { modifyPokemonData } from '@helpers/modifyPokemonData';
import { Pokemon } from '@constants/interfaces';

interface Props {
  filteredPokemonData: Pokemon[];
}

export default function Home({ filteredPokemonData }: Props) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-lg mx-auto mt-auto px-4 py-8">
        <h1 className="text-4xl font-bold mb-8 text-center">Gen 1 Pokédex</h1>
        <Pokedex pokemonData={filteredPokemonData} />
      </main>
      <footer className="w-full bg-gray-800 text-white py-5 text-center">
        &copy; 2022 My Site
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps<Props> = async (): Promise<{
  props: Props;
}> => {
  const response = await fetchPokedex({ limit: 151 });
  const data = response.results;
  const pokemonData = await Promise.all(
    data.map((pokemon: Pokemon, idx: number) => {
      const id = idx + 1;
      return fetchPokemon({ id }).then((pokemonWithDetails: Pokemon) => {
        return { ...pokemonWithDetails, url: pokemon.url };
      });
    })
  );
  const filteredPokemonData = modifyPokemonData(pokemonData);
  return { props: { filteredPokemonData } };
};
